### ISSUE TITLE
Echo notification next to user name.

### ISSUE THREAD

**Issue by innosflew** [ElNovi/mediawiki-skins-Timeless#1]
This is one of the best skins out there, and everything works perfectly so far, but it would be nice and more practical to have the echo notification next to the username instead of the dropdown of the username.

**Comment by ElNovi** [comment]
Yep it would be great, but i didn't figure out how to do it. If anyone knows - feel free to commit the fix.

**Comment by zaori** [comment]
This is also tracked in phabricator: https://phabricator.wikimedia.org/T131738
